# Generated by Django 4.1.7 on 2023-02-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100, verbose_name='user Name')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('pw', models.CharField(max_length=100, verbose_name='password')),
                ('cpw', models.CharField(max_length=100, verbose_name='conform password')),
            ],
        ),
    ]
