# Generated by Django 4.1.7 on 2023-02-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='cpw',
        ),
        migrations.AddField(
            model_name='member',
            name='fname',
            field=models.CharField(default='jane doe', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(default='00', max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='pw',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='uname',
            field=models.CharField(max_length=100),
        ),
    ]
