# Generated by Django 4.1.7 on 2023-04-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_service_photo_remove_service_scharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('crate', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=100)),
                ('cno', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plansn', models.CharField(max_length=20)),
                ('plandes', models.CharField(max_length=100)),
                ('planamt', models.CharField(max_length=10)),
            ],
        ),
    ]
