# Generated by Django 4.1.7 on 2023-04-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_camera_plans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
