# Generated by Django 4.1.7 on 2023-04-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusname', models.CharField(max_length=20)),
                ('creview', models.CharField(max_length=100)),
            ],
        ),
    ]
