# Generated by Django 4.1.7 on 2023-04-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_payment_alter_service_des'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cardname',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='cardno',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='cvv',
            new_name='customername',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='expmonth',
            new_name='plan',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='expyear',
        ),
    ]
