# Generated by Django 4.1.7 on 2023-05-03 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_cardname_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.ForeignKey(default='email', on_delete=django.db.models.deletion.CASCADE, to='myapp.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plans',
            name='plandes',
            field=models.CharField(max_length=500),
        ),
    ]
