# Generated by Django 4.1.7 on 2023-05-03 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_member_id_payment_email_alter_member_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=models.ForeignKey(default='id', on_delete=django.db.models.deletion.CASCADE, to='myapp.member'),
        ),
    ]
