# Generated by Django 4.1.7 on 2023-05-03 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('plan', models.CharField(max_length=20)),
                ('email', models.ForeignKey(default='id', on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
            ],
        ),
    ]
